#! /bin/bash

export VERSION="43"
export SYSTEM_DESC="ChimeraOS"
export SYSTEM_NAME="chimeraos"
export CODENAME="Agni"
export USERNAME="gamer"
export SIZE="10000MB"
export ARCHIVE_DATE=""
export WEBSITE="https://chimeraos.org"
export DOCUMENTATION_URL="https://chimeraos.org/about"
export BUG_REPORT_URL="https://github.com/ChimeraOS/chimeraos/issues"

export KERNEL_PACKAGE="linux-chimeraos"
export KERNEL_PACKAGE_ORIGIN="local"

export PACKAGES="\
	accountsservice \
	alsa-firmware \
	alsa-utils \
	amd-ucode \
	bluez \
	bluez-hid2hci \
	bluez-plugins \
	bluez-utils \
	cifs-utils \
	diffutils \
	dkms \
	dmidecode \
	dosbox \
	eog \
	epiphany \
	ethtool \
	evtest \
	ffmpeg \
	file-roller \
	firejail \
	flatpak \
	fmt \
	fuse-zip \
	fuse2 \
	gamemode \
	git \
	gnome-console \
	gnome-control-center \
	gnome-disk-utility \
	gnome-keyring \
	gnome-session \
	gnome-shell \
	gnome-software \
	gnome-text-editor \
	gst-plugin-pipewire \
	haveged \
	htop \
	lib32-curl \
	lib32-fontconfig \
	lib32-freetype2 \
	lib32-gamemode \
	lib32-libgpg-error \
	lib32-libnm \
	lib32-libxinerama \
	lib32-libxcrypt-compat \
	lib32-openal \
	lib32-pipewire \
	lib32-systemd \
	lib32-vulkan-icd-loader \
	libcurl-gnutls \
	libidn11 \
	libretro-beetle-pce-fast \
	libretro-beetle-psx-hw \
	libretro-citra \
	libretro-desmume \
	libretro-dolphin \
	libretro-flycast \
	libretro-genesis-plus-gx \
	libretro-kronos \
	libretro-mame \
	libretro-mesen-s\
	libretro-mgba \
	libretro-mupen64plus-next \
	libretro-nestopia \
	libretro-pcsx2 \
	libretro-picodrive \
	libretro-ppsspp \
	libretro-snes9x \
	libva-intel-driver \
	libva-vdpau-driver \
	libxcrypt-compat \
	libxss \
	lightdm \
	linux-firmware \
	logrotate \
	lshw \
	mesa-demos \
	nano \
	nautilus \
	networkmanager \
	nfs-utils \
	nss-mdns \
	openal \
	openssh \
	pipewire \
	pipewire-alsa \
	pipewire-jack \
	pipewire-pulse \
	podman \
	pulsemixer \
	python \
	python-inotify-simple \
	retroarch \
	rsync \
	smbclient \
	sof-firmware \
	sshfs \
	steam \
	sudo \
	ttf-liberation \
	unzip \
	usb_modeswitch \
	usbutils \
	vim \
	vulkan-icd-loader \
	wavpack \
	wget \
	which \
	wireplumber \
	xdg-desktop-portal \
	xdg-desktop-portal-gnome \
	xdg-desktop-portal-wlr \
	xdg-user-dirs-gtk \
	xf86-video-amdgpu \
	xorg-server \
"

export PACKAGE_OVERRIDES="\
	https://github.com/BoukeHaarsma23/chimera-packages/releases/download/chos-f4379b6/gamescope-git-3.12.0.beta8.r11.g789cfc9-1-x86_64.pkg.tar.zst
	https://github.com/BoukeHaarsma23/chimera-packages/releases/download/chos-f4379b6/gamescope-session-hdr-git-r163.9a443bf-1-any.pkg.tar.zst
	https://github.com/BoukeHaarsma23/chimera-packages/releases/download/chos-f4379b6/lib32-mangohud-0.6.9.1.r68.g0ae2e42-1-x86_64.pkg.tar.zst
	https://github.com/BoukeHaarsma23/chimera-packages/releases/download/chos-f4379b6/linux-chimeraos-6.4.chos1-1-x86_64.pkg.tar.zst
	https://github.com/BoukeHaarsma23/chimera-packages/releases/download/chos-f4379b6/linux-chimeraos-headers-6.4.chos1-1-x86_64.pkg.tar.zst
	https://github.com/BoukeHaarsma23/chimera-packages/releases/download/chos-f4379b6/mangohud-0.6.9.1.r68.g0ae2e42-1-x86_64.pkg.tar.zst
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.3-chos1/lib32-libva-mesa-driver-23.1.3.chos1-1-x86_64.pkg.tar.zst
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.3-chos1/lib32-mesa-23.1.3.chos1-1-x86_64.pkg.tar.zst
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.3-chos1/lib32-mesa-vdpau-23.1.3.chos1-1-x86_64.pkg.tar.zst
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.3-chos1/lib32-vulkan-intel-23.1.3.chos1-1-x86_64.pkg.tar.zst
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.3-chos1/lib32-vulkan-radeon-23.1.3.chos1-1-x86_64.pkg.tar.zst
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.3-chos1/libva-mesa-driver-23.1.3.chos1-1-x86_64.pkg.tar.zst
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.3-chos1/mesa-23.1.3.chos1-1-x86_64.pkg.tar.zst
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.3-chos1/mesa-vdpau-23.1.3.chos1-1-x86_64.pkg.tar.zst
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.3-chos1/vulkan-intel-23.1.3.chos1-1-x86_64.pkg.tar.zst
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.3-chos1/vulkan-mesa-layers-23.1.3.chos1-1-x86_64.pkg.tar.zst
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.3-chos1/vulkan-radeon-23.1.3.chos1-1-x86_64.pkg.tar.zst
"

export AUR_PACKAGES="\
	boxtron \
	chimera \
	chimeraos-device-quirks-git \
	drm_info-git \
	frzr \
	handygccs-git \
	hhfc-git \
	legendary \
	libretro-opera-git \
	libretro-prosystem-git \
	libretro-stella2014-git \
	libretro-virtualjaguar-git \
	nintendo-udev \
	opengamepadui-bin \
	opengamepadui-session-git \
	pikaur \
	python-vdf \
	retroarch-autoconfig-udev-git \
	rz608-fix-git \
	steam-removable-media-git \
	ttf-kanit \
	wyvern \
	xpad-noone-dkms \
	xpadneo-dkms \
"

export SERVICES="\
	NetworkManager \
	avahi-daemon \
	bluetooth \
	bluetooth-workaround \
	chimera-proxy.service \
	chimera-proxy.socket \
	fstrim.timer \
	handycon \
	haveged \
	lightdm \
	sshd \
	systemd-timesyncd \
"

export USER_SERVICES="\
	chimera.service \
	gamemoded.service \
	ryzen-tctl \
	steam-patch.service \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/libretro/autoconfig/udev/Gasia_PS_Gamepad_USB.cfg \
	/usr/share/libretro/autoconfig/udev/Sony-PlayStation3-DualShock3-Controller-Bluetooth.cfg \
	/usr/share/libretro/autoconfig/udev/Xbox_360_Wireless_Receiver_Chinese01.cfg \
	/usr/share/man \
"

postinstallhook() {
	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/dmidecode -t 11
	" > /etc/sudoers.d/steam
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-gamescope
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-lightdm
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/share/chimera/bin/power-tool
	" > /etc/sudoers.d/chimera

	# disable retroarch menu in joypad configs
	find /usr/share/libretro/autoconfig -type f -name '*.cfg' | xargs -d '\n' sed -i '/input_menu_toggle_btn/d'

	# download and add racing wheel udev rules
	pushd /usr/lib/udev/rules.d
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-fanatec-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-logitech-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-thrustmaster-wheel-perms.rules
	popd

	# Remove build tools for slimmer image
	rm /usr/share/libalpm/hooks/70-dkms-install.hook
	rm /usr/share/libalpm/hooks/70-dkms-upgrade.hook
	rm /usr/share/libalpm/hooks/71-dkms-remove.hook
	pacman --noconfirm -Rnsdd make gcc dkms ${KERNEL_PACKAGE}-headers

	# remove dolphin standalone emulator files (only need /usr/share/dolphin-emu/sys)
	rm /usr/bin/dolphin-emu
	rm /usr/bin/dolphin-emu-nogui
	rm /usr/bin/dolphin-tool
	rm /usr/share/applications/dolphin-emu.desktop

	# clean up desktop shortcuts
	sed -i -e 's/Name=Steam (Runtime)/Name=Steam/' /usr/share/applications/steam.desktop
	find /usr/share/applications/* | \
	grep -v org.chimeraos.Gamescope.desktop | \
	grep -v org.chimeraos.app.desktop | \
	grep -v org.gnome.Console.desktop | \
	grep -v org.gnome.DiskUtility.desktop | \
	grep -v org.gnome.FileRoller.desktop | \
	grep -v org.gnome.Nautilus.desktop | \
	grep -v org.gnome.Settings.desktop | \
	grep -v org.gnome.Software.desktop | \
	grep -v org.gnome.TextEditor.desktop | \
	grep -v steam.desktop | \
	xargs -I {} sh -c "echo NoDisplay=true >> {}"

	# force -steamdeck option in desktop mode to prevent constant steam updates
	sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/steam-runtime -steamdeck,' /usr/share/applications/steam.desktop
}
