name: System image build

env:
  REGISTRY: ghcr.io

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - 'master'

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Changes check
    # Required permissions
    permissions:
      pull-requests: read
    outputs:
      require-rebuild: ${{ steps.filter.outputs.require-rebuild }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            require-rebuild:
              - 'Dockerfile'
              - 'manifest'
              - 'pkgs/**'

  build-docker-image:
    name: Build and publish docker container
    needs: changes
    if: ${{ needs.changes.outputs.require-rebuild == 'true' }}
    uses: ./.github/workflows/build.yml

  list-pkgbuilds:
    name: List AUR packages
    runs-on: ubuntu-latest
    outputs:
      aur-pkgs: ${{ steps.set-aur-pkgs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-aur-pkgs
        run: source ./manifest ; echo "matrix=$(echo ${AUR_PACKAGES} | jq -R -s -c 'split(" ")[:-1]')" >> $GITHUB_OUTPUT
        shell: bash

  aur-pkgbuild:
    needs:
     - build-docker-image
     - list-pkgbuilds
    if: ${{ !cancelled() && (success() || failure() || needs.build-docker-image.result == 'skipped') }}
    name: Build AUR package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package: ${{ fromJson(needs.list-pkgbuilds.outputs.aur-pkgs) }}
    steps:
      - name: Set repo name to lowercase
        run: echo IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Build packages
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master
          docker run --rm -v $(pwd):/workdir --entrypoint=/workdir/aur-pkgs/build-aur-package.sh ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master ${{ matrix.package }}
      - name: Upload Package Archives
        uses: actions/upload-artifact@v3
        with:
            name: AUR-packages
            path: aur-pkgs/*.pkg.tar*

  build:
    needs:
     - build-docker-image
     - aur-pkgbuild
    if: ${{ !cancelled() && (success() || failure() || needs.build-docker-image.result == 'skipped') }}
    name: Build ChimeraOS image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.build_image.outputs.version }}
      display_name: ${{ steps.build_image.outputs.display_name }}
      display_version: ${{ steps.build_image.outputs.display_version }}
      image_filename: ${{ steps.build_image.outputs.image_filename }}
    steps:
      - name: set repo name to lowercase
        run: echo IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
            name: AUR-packages
            path: aur-pkgs/
      - name: Build system image
        id: build_image
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master
          docker run -u root --rm --entrypoint=/workdir/build-image.sh -v $(pwd):/workdir -v $(pwd)/output:/output -v $GITHUB_OUTPUT:$GITHUB_OUTPUT -e "GITHUB_OUTPUT=$GITHUB_OUTPUT" --privileged=true ghcr.io/boukehaarsma23/chimeraos-packages:master $(echo ${GITHUB_SHA} | cut -c1-7)
          echo -e "$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master)" > output/container.txt
      - if: github.ref != 'refs/heads/master'
        name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: Output
          path: output/
      - if: github.ref == 'refs/heads/master'
        name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.build_image.outputs.version }}
          name: ${{ steps.build_image.outputs.display_name }} ${{ steps.build_image.outputs.display_version }} [UNSTABLE]
          draft: false
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            output/${{ steps.build_image.outputs.image_filename }}
            output/build_info.txt
            output/sha256sum.txt
            output/container.txt
